== Gradle Setup

First, add the Koin dependency like below:

.build.gradle
[source,gradle]
----
// Add Jcenter to your repositories if needed
repositories {
    jcenter()    
}
dependencies {
    // Koin for Kotlin apps
    compile 'org.koin:koin-core:{{ site.current_version }}'
}
----

== Target

This getting started tutorial makes you write simple components and wire
them in a simple & pure Kotlin app.

The idea is to wire some components and inject them in an Application class.

== Data & Service components

Let's create a `HelloModel` data class to provide simple data:

.HelloModel.kt
[source,kotlin]
----
data class HelloModel(val message : String = "Hello Koin!")
----

Let's create a service to use our `HelloModel`. Let's write `HelloServiceImpl` class and its interface `HelloService`:

.HelloService.kt
[source,kotlin]
----
// Service interface
interface HelloService {
    fun hello(): String
}

// service class with injected helloModel instance
class HelloServiceImpl(private val helloModel: HelloModel) : HelloService {

    override fun hello() = "Hello ${helloModel.message}"
}
----


== A simple application

To retrieve our `HelloService` component, we need to create a Koin runtime component. Let's write a `HelloApplication` class, and tag it with `KoinComponent` interface. This will later allows us to use the `by inject()` operators, to retrieve our component: 

.HelloApplication.kt
[source,kotlin]
----
class HelloApplication : KoinComponent {

    // Inject service
    val helloService by inject<HelloService>()

    fun sayHello() = println(helloService.hello())
}
----


== Declaring dependencies & Start Koin

.module.kt
[source,kotlin]
----
val helloModule = module {
    single { HelloModel() }
    single { HelloServiceImpl(get()) as HelloService }
}
----

Let's start our app from a `main` function:

.HelloApplication.kt
[source,kotlin]
----
fun main(vararg args: String) {
    startKoin(listOf(helloModule))
    HelloApplication().sayHello()
}
----


== What's Next?


